#!/sbin/busybox sh

cd /

mount -t proc proc /proc
mount -t sysfs sys /sys

mkdir -p /dev/block
mkdir /dev/input

for i in 0 1 2 3 4 5; do
        event=$((0+$i))
        minor=$((64+$i))
        mknod /dev/input/event$event c 13 $minor
done

for i in 0 1 2; do
	block=$((10+$i))
	minor=$((2+$i))
	mknod /dev/block/mmcblk0p$block b 259 $minor
done

mknod /dev/block/loop0 b 7 0

mount -t ext4 /dev/block/mmcblk0p12 /data

out() {
	umount -f /system
	umount -f /data

	chmod 755 /init
	chmod 644 /*.tuna
	chmod 644 /*.rc
	chmod 644 /*.prop
	chmod -R 755 /lib

	exec /init
}

mkdir -p /data/media/0/romswitcher
if [ -e /data/media/0/romswitcher/manualboot ]; then
	if [ -e /data/media/.nextboot ]; then
		rm -f /data/media/.nextboot
	else
		mv -f /res/etc /
		mv -f /res/aosp43/* /
		mv -f /res/recovery/* /
		mv -f /init.rc.2 /init.rc
		out
	fi
else
	echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
	KEY=`/sbin/ext/evkey -u -t 2000 /dev/input/event2`
	if [ "$KEY" == "116" ]; then
		KEYNEXT=`/sbin/ext/evkey -u -t 500 /dev/input/event2`
		if [ "$KEYNEXT" == "116" ]; then
			echo 300 > /sys/devices/virtual/timed_output/vibrator/enable
			echo 1 > /data/media/rebootrs
		else
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			echo 1 > /data/media/.rom
		fi
	elif [ "$KEY" == "114" ]; then
		KEYNEXT=`/sbin/ext/evkey -u -t 500 /dev/input/event2`
		if [ "$KEYNEXT" == "114" ]; then
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			sleep 0.3
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			sleep 0.3
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			sleep 0.3
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			echo 4 > /data/media/.rom
		else
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			sleep 0.3
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			echo 2 > /data/media/.rom
		fi
	elif [ "$KEY" == "115" ]; then
		KEYNEXT=`/sbin/ext/evkey -u -t 500 /dev/input/event2`
		if [ "$KEYNEXT" == "115" ]; then
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			sleep 0.3
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			sleep 0.3
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			sleep 0.3
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			sleep 0.3
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			echo 5 > /data/media/.rom
		else
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			sleep 0.3
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			sleep 0.3
			echo 50 > /sys/devices/virtual/timed_output/vibrator/enable
			echo 3 > /data/media/.rom
		fi
	fi
fi

[ -e /data/media/.nextboot ] && rm -f /data/media/.nextboot

if [ -e /data/media/rebootrs ]; then
	rm -f /data/media/rebootrs
	mv -f /res/etc /
	mv -f /res/aosp44/* /
	mv -f /res/recovery/* /
	out
fi

[ -e /data/media/.rom ] || echo 1 > /data/media/.rom
ROM=`cat /data/media/.rom`
[ $ROM == 0 ] && ROM=1

if [ "$ROM" == "1" ]; then
	mount -t ext4 -o rw /dev/block/mmcblk0p10 /system
else
	mount --bind /data/media/.${ROM}rom/system /system
fi

if grep -q ro.build.version.sdk=19 /system/build.prop ; then
	mv -f /res/aosp44/* /
else
	mv -f /res/aosp43/* /
fi

[ "$ROM" == "1" ] || mv -f /fstab.tuna.romswitcher /fstab.tuna

[ -d /system/app/Synapse.apk ] || mv -f /res/synapse/Synapse.apk /system/app/ && chmod 644 /system/app/Synapse.apk

out
